version: '3'
services:
    nginx:
        image: nginx
        ports:
            - 80:80
            - 443:443
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf:ro
            - /etc/letsencrypt/live/jenkins.here-city.kro.kr/fullchain.pem:/etc/letsencrypt/live/jenkins.here-city.kro.kr/fullchain.pem:ro
            - /etc/letsencrypt/live/jenkins.here-city.kro.kr/privkey.pem:/etc/letsencrypt/live/jenkins.here-city.kro.kr/privkey.pem:ro
        depends_on:
            - jenkins

    jenkins:
        image: jenkins/jenkins:lts
        ports:
            - 8080:8080
            - 50000:50000
        volumes:
            - jenkins_data:/var/jenkins_home

volumes:
    jenkins_data:
