version: 0.0
os: linux

files:
  - source: /
    destination: /home/ubuntu/here-city
permissions:
  - object: /
    pattern: "**"
    owner: ubuntu
    group: ubuntu

hooks:
  AfterInstall:
    - location: build.sh
      timeout: 60
      runas: ubuntu
