version: 0.2
phases:
  build:
    commands:
      - echo Build Starting on `date`
      - chmod +x ./gradlew
      - ./gradlew build
  post_build:
    commands:
      - echo $(basename ./build/generated/source/kapt/*.jar)
      - pwd
artifacts:
  files:
    - build/generated/source/kapt/*.jar
    - appspec.yaml
    - scripts/**
  discard-paths: yes
cache:
  paths:
    - '/root/.gradle/caches/**/*'
