spring:
    application:
        name: here-city-api
    profiles:
        active: prod
    sleuth:
        enabled: true
        sampler:
            probability: 1.0
        trace-id128: true
        baggage:
            correlation-enabled: true

---

spring:
    application:
        name: here-city-api
    profiles:
        active: local
    sleuth:
        enabled: true
        sampler:
            probability: 1.0
        trace-id128: true
        baggage:
            correlation-enabled: true
