version: '3.6'

services:
  mariadb:
    container_name: mariadb
    build:
      context: ./mariadb
      dockerfile: mariadb.dockerfile
    ports:
      - "14306:3306"
    restart: always
    volumes:
      - ./mariadb/data:/data
    env_file:
      - ./mariadb/.env
  
  redis-stack:
    container_name: redis-stack
    image: 'redis/redis-stack:latest'
    ports:
      - '7001:6379'
    environment:
      - 'REDIS_ARGS=--appendonly yes'
    volumes:
      - ./redis/data:/data
