version: '3.6'

services:
  mariadb:
    container_name: mariadb
    build:
      context: ./mariadb
      dockerfile: mariadb.dockerfile
    ports:
      - "14306:3306"
    restart: always
    volumes:
      - ./mariadb/data:/data
    env_file:
      - ./mariadb/.env
  
  redis:
    container_name: redis
    image: redis:alpine
    ports:
      - '7001:6379'
    volumes:
      - ./redis/data:/data
