version: '3.6'

services:
  nginx:
    image: nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/letsencrypt/live/api.here-city.kro.kr/fullchain.pem:/etc/letsencrypt/live/api.here-city.kro.kr/fullchain.pem:ro
      - /etc/letsencrypt/live/api.here-city.kro.kr/privkey.pem:/etc/letsencrypt/live/api.here-city.kro.kr/privkey.pem:ro

  mariadb:
    container_name: mariadb
    build:
      context: ./mariadb
      dockerfile: mariadb.dockerfile
    ports:
      - "14306:3306"
    restart: always
    volumes:
      - ./mariadb/data:/data
    env_file:
      - ./mariadb/.env

  redis:
    container_name: redis
    image: redis:alpine
    ports:
      - '7001:6379'
    volumes:
      - ./redis/data:/data
