version: 0.0
os: linux

files:
  - source: /
    destination: /home/ubuntu/build
    overwrite: true
permissions:
  - object: /
    pattern: "**"
    owner: ubuntu
    group: ubuntu

hooks:
  ApplicationStart:
    - location: build.sh
      timeout: 60
      runas: root
